repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.37.3
  hooks:
  - id: pyupgrade
    args: [--py37-plus]
- repo: https://github.com/python/black
  rev: 22.8.0
  hooks:
  - id: black
    exclude: docopt.py
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear==22.1.11]
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==22.1.0]
